configuration:
  token: ''
  bot_playing_activity: 'jogar.potocraft.com'
  operator_role_name: 'Operador'
  removed_messages:
    category_name: "Moderação privado"
    channel_name: "Mensagens-removidas"
    cached_time_in_seconds: 120
  tickets:
    category_name: 'Tickets'
    lobby_channel_name: 'Iniciar-ticket'
  mentions_user_timeout_seconds: 300
  blocked_word_user_timeout_seconds: 300
  blocked_words:
    - puta
    - whore
    - prostituta
    - cacete
    - caceta
    - fudida
    - fudido
    - fodida
    - fodido
    - fudeu
    - fudeo
    - fodeu
    - fodendo
    - fudendo
    - foda
    - foder
    - fode
    - hooker
    - escort
    - bicha
    - bixa
    - buceta
    - caralho
    - caralha
    - porra
    - viado
    - viada
    - veado
    - veada
    - viadao
    - veadao
    - xoxota
    - xana
    - chochota
    - xochota
    - choxota
    - chana
    - xereca
    - xerereca
    - xavasca
    - chereca
    - cherereca
    - chavasca
    - baitola
    - bisca
    - biscate
    - busseta
    - bosseta
    - cadela
    - xota
    - chota
    - corna
    - corno
    - gay
    - gey
    - guei
    - guay
    - guai
    - gai
    - gei
    - leprosa
    - leproso
    - merda
    - merd
    - mierd
    - mierda
    - merdao
    - bostao
    - bosta
    - retardado
    - retardada
    - veado
    - quenga
    - kenga
    - fedido
    - fedida
    - mulata
    - mulato
    - nega
    - negao
    - nego
    - negona
    - anus
    - preta
    - encardido
    - encardida
    - fuleiro
    - fuleira
    - fulero
    - fulera
    - foleiro
    - foleira
    - folero
    - folera
    - vadia
    - vadio
    - raba
    - rabo
    - suruba
    - surubao
    - soruba
    - sorubao
    - suroba
    - surobao
    - cachorra
    - vagabunda
    - vagabundo
    - corninho
    - corninha
    - cornao
    - cornona
    - safada
    - safado
    - estupido
    - estupida
    - istupido
    - istupida
    - cuzao
    - cuzona
    - cuzinho
    - fdp
    - fds
    - vsfd
    - sfd
    - vsf
    - tnc
    - vtnc
    - putinha
    - putinho
    - putona
    - putao
    - fela
    - poha
    - putaria
    - putasa
    - putassa
    - putaca
    - arrombado
    - arrombada
    - arombado
    - arombada
    - chupa
    - xupa
    - hermafrodita
    - emafrodita
    - aborto
    - aborta
    - abortado
    - abortada
    - anal
    - lixo
    - lixao
    - lixona
    - licho
    - lichao
    - lichona
    - gozei
    - goza
    - gozar
    - gozo
    - goso
    - gosei
    - gosa
    - gosar
    - zoofilo
    - zoofila
    - zofilo
    - zofila
    - garai
    - carai
    - karai
    - pinto
    - piroca
    - penis
    - pirocao
    - birosca
    - pintao
    - pauzao
    - pausudo
    - pauzudo
    - pausao
    - piranha
    - piranhona
    - escroto
    - escrota
    - escrotao
    - macaco
    - macaca
    - retarda
    - debiloide
    - porno
    - pornozao
    - mama
    - mamando
    - zona
    - putaria
    - cock
    - ball
    - bola
    - novinha
    - 9vinha
    - 9inha
    - rabuda
    - lambuzar
    - lambuza
    - grelo
    - greluda
    - grelao
    - monobola
    - monoball
    - boludo
    - boluda
    - burro
    - burra
    - babaca
    - cretino
    - cretina
    - piroquinha
    - pirokinha
    - vagina
    - nude
    - nigga
    - niga
    - nigger
    - niger
    - cu
    - fude
    - fuder
    - merdinha
    - desgraça
    - desgraçado
    - desgraçada
    - peste
    - piriguete
    - pirigete
    - ass
    - pussy
    - pica
    - dick
    - fuck
    - fucking
    - fucked
    - poura
    - porra
    - perereca
    - fodase
    - favelado
    - favelada
    - pepeca

language:
  message_mentions_user_directly: "[ mensagem apagada: _menciona algum usuário diretamente, não faça isso. Se precisar de ajuda, crie um ticket!_ ]"
  tickets:
    open_ticket_message: |
      **Seja bem vindo a PotoCraft!**
      
      Aqui você pode:
      ```
      - Fazer denúncias,
      - Tirar dúvidas,
      - Fazer sugestões,
      - Ativar compras realizadas pelo site.
      ```
      Antes de prosseguir, leia atentamente **as regras de comunicação**:
      ```
      - Não marque as pessoas,
      - Mantenha o respeito,
      - Não aguarde a resposta, já conte o que você precisa ou quer
      - Não abra um ticket e suma
      ```
      Agora, se quiser continuar com o suporte dos moderadores e administração, clique abaixo:
    ticket_channel_created_message: |
      **Um ticket foi aberto para você!**
      
      Veja o canal %channel_link% clicando aqui e siga as instruções.
    ticket_channel_already_exists: |
      **Já existe um ticket em aberto!**
      
      Aguarde o encerramento antes de abrir uma nova requisição.
      Caso o caso já foi encerrado, você pode fechar o canal através da mensagem do bot em %channel_link%.
    ticket_opened_instructions_message: |
      Olá, %user_link%!

      Este é um ambiente seguro entre você e a moderação! **Apenas você poderá ver o que é conversado aqui.**
      
      Ao clicar no botão abaixo, o _ticket_ será encerrado e você deixará de ver as mensagens.
    ticket_closing_message: 'Fechando este ticket...'
