configuration:
  damage_modifiers:
    overall_damage_dealt_multiplier: 0.885
    pvp_damage_multiplier: 1.125
    armor_damage_reduction_multiplier: 0.845
    enchantment_damage_reduction_multiplier: 0.793
    damage_cooldown_factor: 0.72
    arrow_damage_multiplier: 1.5
    arrow_velocity_multiplier: 1.0
    arrow_affected_by_gravity: true
  villager:
    prevent_all_enchanted_books: false
    prevent_treasure_enchanted_books: true
    nerf_enchanted_books: true
  damage_effects:
    damage_particle_amount: 156
    spawn_lightning_on_dead: true
    spawn_firework_on_killer: true
  webhook_url: ""
  enable_player_logging: true
  hide_join_quit_messages: false
  delay_between_death_messages_seconds: 90
  delay_between_login_messages_seconds: 45
  experience_modifier:
    enabled: true
    default_modifier: 0.8
    groups:
      potocraft.exp_modifier.vip: 1.4
  dropped_experience:
    enabled: true
    # The sum must be lower than the inverse of the highest experience modifier
    kept_ratio: 0.6
    dropped_ratio: 0.1
  drop_player_heads:
    enabled: true
    item_lore:
      - "<dark_aqua>Cabeça de <yellow><bold><killed></bold></yellow>"
      - "<dark_aqua>Conquistada por <yellow><bold><killer></bold></yellow></dark_aqua>"
      - "<dark_aqua>em <yellow><datetime></yellow></dark_aqua>"
  rainy_night_event:
    enabled: false
    potion_effects:
      - type: 'health_boost'
        duration: 7200
        amplifier: 4
      - type: 'strength'
        duration: 7200
        amplifier: 1
  lava_flow:
    allow_lava_flow: false
    allow_lava_flow_worlds:
      - mundo_nether
  game_difficulty: normal
  game_rules_applied:
    default:
      playersSleepingPercentage: 35
    world:
      doFireTick: false
      maxEntityCramming: 4
  worlds_with_synced_real_time:
    - world
  world_borders_radius:
    world_nether: 30000000.0
  per_world_pvp_settings:
    default:
      prevent_night_skip: true
      use_constant_pvp_setting: true
      constant_pvp_setting: false
      start_pvp_time: 14500
      end_pvp_time: 23200
    world_nether:
      use_constant_pvp_setting: true
      constant_pvp_setting: true
    world_the_end:
      use_constant_pvp_setting: true
      constant_pvp_setting: false

language:
  commands:
    player_only: "<red>Comando disponível apenas para jogadores</red>"
    player_not_found: "<red>Jogador não encontrado!</red>"
    player_time:
      help: "<gold>Uso: <yellow>/tempo (dia/meiodia/noite/meianoite) [fixo]</yellow></gold>"
    player_weather:
      help: "<gold>Uso: <yellow>/clima (limpo/chuvoso)</yellow></gold>"
    gamemode:
      help: "<gold>Uso: <yellow>/gamemode (survival/creative/spectator/adventure) [nome]</yellow></gold>"
    enchant:
      help: "<gold>Uso: <yellow>/enchant (encantamento)</yellow></gold>"
      cant_enchant_item: "<red>Não é possível encantar este item</red>"
    kill:
      help: "<gold>Uso: <yellow>/kill (nome)</yellow></gold>"
    fly:
      help: "<gold>Uso: <yellow>/fly [nome]</yellow></gold>"
      status: "<gold><yellow><username></yellow> está com modo de voo <yellow><flying></yellow></gold>"
