configuration:
  damage_modifiers:
    overall_damage_dealt_multiplier: 0.885
    pvp_damage_multiplier: 1.125
    armor_damage_reduction_multiplier: 0.845
    enchantment_damage_reduction_multiplier: 0.793
    damage_cooldown_factor: 0.72
  villager:
    prevent_all_enchanted_books: false
    prevent_treasure_enchanted_books: true
    nerf_enchanted_books: true
  damage_effects:
    damage_particle_amount: 156
    spawn_lightning_on_dead: true
    spawn_firework_on_killer: true
  enable_player_logging: true
  hide_join_quit_messages: false
  delay_between_death_messages_seconds: 90
  delay_between_login_messages_seconds: 45
  experience_modifier:
    enabled: true
    default_modifier: 0.8
    groups:
      potocraft.exp_modifier.vip: 1.4
  rainy_night_event:
    enabled: false
    potion_effects:
      - type: 'health_boost'
        duration: 7200
        amplifier: 4
      - type: 'strength'
        duration: 7200
        amplifier: 1
  lava_flow:
    allow_lava_flow: false
    allow_lava_flow_worlds:
      - mundo_nether
  game_difficulty: normal
  game_rules_applied:
    default:
      playersSleepingPercentage: 35
    world:
      doFireTick: false
      maxEntityCramming: 4
  worlds_with_synced_real_time:
    - world
  per_world_pvp_settings:
    default:
      prevent_night_skip: true
      use_constant_pvp_setting: true
      constant_pvp_setting: false
      start_pvp_time: 14500
      end_pvp_time: 23200
    world_nether:
      use_constant_pvp_setting: true
      constant_pvp_setting: true
    world_the_end:
      use_constant_pvp_setting: true
      constant_pvp_setting: false

language:

  commands:
    player_only: "&cComando disponível apenas para jogadores"
    player_not_found: "&cJogador não encontrado!"
    player_time:
      help: "&6Uso: &e/tempo (dia/meiodia/noite/meianoite) [fixo]"
    player_weather:
      help: "&6Uso: &e/clima (limpo/chuvoso)"
    vanish:
      player_vanished: "&6Ficou invisível."
      player_appeared: "&6Ficou visível."
    gamemode:
      help: "&6Uso: &e&l/gamemode (creative/spectator/survival/adventure)"
    enchant:
      help: "&6Uso: &e&l/enchant (encantamento)"
      cant_enchant_item: "&cNão é possível encantar este item"
    kill:
      help: "&6Uso: &e&l/kill (nome)"
