name: ServerUtility
main: com.rafaelsms.potocraft.serverutility.ServerUtilityPlugin
version: 0.1
api-version: 1.18
author: rafaelsms
website: rafaelsms.com
description: Utility plugin for PotoCraft.
load: STARTUP
