name: ServerUtility
main: com.rafaelsms.potocraft.serverutility.ServerUtilityPlugin
version: 0.1
api-version: 1.18
author: rafaelsms
website: rafaelsms.com
description: Utility plugin for PotoCraft.
load: STARTUP
commands:
  enderchest:
    description: Opens your enderchest wherever you are.
    aliases: [ ec, bauender ]
  workbench:
    description: Opens a workbench wherever you are.
    aliases: [ wb, craft, bancada ]
  anvil:
    description: Opens an anvil wherever you are.
    aliases: [ bigorna ]
  playertime:
    description: Sets your world time to your taste.
    aliases: [ ptime, tempo, time ]
  playerweather:
    description: Sets your world weather to your taste.
    aliases: [ pweather, clima, weather ]
  vanish:
    description: Hides/shows yourself to others.
    aliases: [ v ]
  gamemode:
    description: Change your gamemode.
    aliases: [ gm, gmc, gms, gmsp, gma ]
  enchant:
    description: Enchant your item in hand.
    aliases: [ enchantment, encantar, encantamento ]
  suicide:
    description: Kills your player entity.
    aliases: [ suicidar, suicidio ]
