name: ServerUtility
main: com.rafaelsms.potocraft.serverutility.ServerUtilityPlugin
version: 0.1
api-version: 1.18
author: rafaelsms
website: rafaelsms.com
description: Utility plugin for PotoCraft.
load: STARTUP
softdepend:
  - WorldGuard
  - LuckPerms
  - Vulcan
  - LightAntiCheat
commands:
  enderchest:
    description: Opens your enderchest wherever you are.
    aliases: [ ec, bauender ]
  workbench:
    description: Opens a workbench wherever you are.
    aliases: [ wb, craft, bancada, craftingtable, ct ]
  anvil:
    description: Opens an anvil wherever you are.
    aliases: [ bigorna ]
  playertime:
    description: Sets your world time to your taste.
    aliases: [ ptime, tempo, time ]
  playerweather:
    description: Sets your world weather to your taste.
    aliases: [ pweather, clima, weather ]
  gamemode:
    description: Change your gamemode.
    aliases: [ gm, gms, gmc, gmsp, gma ]
  enchant:
    description: Enchant your item in hand.
    aliases: [ enchantment, encantar, encantamento ]
  suicide:
    description: Kills your player entity.
    aliases: [ suicidar, suicidio ]
  kill:
    description: Forcefully kills another player.
    aliases: [ matar ]
  fly:
    description: Enables a player to toggle flight mode.
    aliases: [ flight, voar ]
  sendwebhook:
    description: Sends a Discord Webhook message.
  near:
    description: Shows nearby players around you or around other player.
    aliases: [ proximo, perto ]
  vip:
    description: Shows when your VIP subscription will end.
