name: Hardcore
main: com.rafaelsms.potocraft.hardcore.HardcorePlugin
version: 0.1
api-version: 1.18
author: rafaelsms
website: www.potocraft.com
description: Custom plugin for a Hardcore PotoCraft Server
load: STARTUP
