name: PotoCraft
main: com.rafaelsms.potocraft.papermc.PaperPlugin
version: 0.1
api-version: 1.18
author: rafaelsms
website: rafaelsms.com
description: Custom plugin for PotoCraft Server
load: POSTWORLD
depend:
  - floodgate
commands:
  teleporte:
    description: Allows players to teleport to each other.
    aliases: [ tp, tpa ]
  teleporteaqui:
    description: Allows players to teleport to each other.
    aliases: [ tphere, tpahere ]
  teleporteaceitar:
    description: Accepts the player request to teleport
    aliases: [ tpaceitar, tpaccept, tpsim, tpyes ]
  teleporterecusar:
    description: Denies the player request to teleport
    aliases: [ tprecusar, tpdeny, tpnao, tpno ]
