name: PotoCraft
main: com.rafaelsms.potocraft.papermc.PaperPlugin
version: 0.1
api-version: 1.18
author: rafaelsms
website: rafaelsms.com
description: Custom plugin for PotoCraft Server
load: POSTWORLD
depend:
  - floodgate
