name: GameServer
main: com.rafaelsms.potocraft.gameserver.GameServerPlugin
version: 0.1
api-version: 1.18
author: rafaelsms
website: rafaelsms.com
description: Mini games plugin for PotoCraft.
load: STARTUP
