configuration:
  database:
    mongo_uri: 'mongodb://localhost:27017'
    database_name: 'serverNameDb'
    is_exception_fatal: false
    player_profiles_collection: 'playerProfiles'
    warps_collection: 'warps'
  save_players_task_timer_in_ticks: 3600
  local_chat:
    range: 300.0
    local_format: "<click:suggest_command:'/msg <username> '><hover:show_text:'<gold><yellow>Clique</yellow> aqui para mandar uma mensagem privada para <yellow><bold><username></bold></yellow></gold>'><yellow><prefix><username><suffix></yellow></hover></click><gray>:</gray><reset> <message>"
    no_range_format: "<click:suggest_command:'/msg <username> '><hover:show_text:'<gold><yellow>Clique</yellow> aqui para mandar uma mensagem privada para <yellow><bold><username></bold></yellow></gold>'><yellow><prefix><username><suffix></yellow></hover></click><gray>:</gray><reset> <message>"
    spy_format: "<gray><click:suggest_command:'/msg <username> '><hover:show_text:'<gold><yellow>Clique</yellow> aqui para mandar uma mensagem privada para <yellow><bold><username></bold></yellow></gold>'><username></hover></click>:</gray><reset> <gray><message></gray>"
  teleport:
    teleport_delay_in_ticks: 140
    teleport_cooldown_in_seconds: 120
    teleport_request_duration_in_seconds: 210
  totem_usage_cooldown_in_seconds: 360
  homes:
    default_number_of_homes: 1
    replace_home_timeout_ticks: 2400
    home_number_permission_groups:
      potocraft.homes.vip: 5
  combat:
    player_combat_duration_ticks: 820
    mob_combat_duration_ticks: 260
    should_log_off_destroy_totem_first: false
    blocked_commands:
      - tp
      - tphere
      - warp
      - spawn
      - tpaccept
    hardcore:
      enabled: false
      default_ban_time_in_seconds: 21600
      permission_ban_time_groups:
        potocraft.combat.hardcore.vip: 7200

language:
  date_time_format: "dd' de 'MMM' às 'H'h'mm"
  players_only: "<red>Comando disponível apenas para jogadores."
  could_not_load_profile: "<red>Falha ao acessar banco de dados."
  chat:
    nobody_heard_you: "<click:suggest_command:'!escreva a mensagem aqui'><hover:show_text:'<gold>Por exemplo, envie: <yellow>!olá! alguém quer jogar comigo?</yellow></gold>'><red>Ninguém te ouviu! <gold>Tente gritar: digite <yellow><bold>!</bold></yellow> antes da sua mensagem.</gold></hover></click>"
  combat:
    bar_title: "<red>Se sair ou se a conexão cair, irá morrer!"
    command_is_blocked_while_in_combat: "<red>Este comando está bloqueado em combate."
    unknown_world_name: "mundo desconhecido"
    your_death_location_is: "<red>Você morreu em <yellow><world></yellow> nas coordenadas <yellow>x = <x></yellow>, <yellow>y = <y></yellow>, <yellow>z = <z></yellow>."
    hardcore:
      banned: |
        <red>Você morreu no modo hardcore.
        <red>Poderá entrar às <yellow><expiration_date></yellow>.
  teleport:
    bar_title: "<yellow>Teleportando... Não entre em combate!"
    player_quit: "<red>Teleporte cancelado: pessoa saiu!"
    entered_combat: "<red>Teleporte cancelado: combate iniciado!"
    other_player_is_teleporting: "<red>Teleporte cancelado: outra pessoa teleportando!"
    other_player_is_in_combat: "<red>Teleporte cancelado: outra pessoa em combate!"
    already_teleporting: "<red>Teleporte cancelado: já teleportando!"
    destination_unavailable: "<red>Teleporte cancelado: destino do teleporte não está disponível!"
    in_cooldown: "<red>Teleporte estará indisponível por mais <yellow><cooldown> segundos</yellow>."
    failed: "<red>Teleporte falhou!"
    player_not_found: "<red>Não encontramos alguém com este nome."
    offline_player_location_not_found: "<red>Localização de jogador offline não existe."
    help: "<gold>Para teleportar até alguém, digite <yellow><bold>/teleporte (nome)</bold></yellow>."
    requests:
      teleport_received: |
        <gold>Você recebeu um pedido para <yellow><username></yellow> se teleportar até <yellow><bold>você</bold></yellow>.
        <gold>Digite <click:run_command:'/teleporteaceitar <username>'><hover:show_text:'<gold><yellow>Clique</yellow> para <green>aceitar</green> o teleporte.'><green>/teleporteaceitar</green> para aceitar</hover></click> ou <click:run_command:'/teleporterecusar <username>'><hover:show_text:'<gold><yellow>Clique</yellow> para <red>recusar</red> o teleporte.'><red>/teleporterecusar</red> para recusar</hover></click>.
      not_updated: "<red>Pedido de teleporte anterior precisa ser cancelado por <yellow><username></yellow> primeiro ou digitando <yellow><bold>/teleportecancelar</bold></yellow>."
      sent: "<gold>Pedido de teleporte enviado a <yellow><username></yellow>."
      no_found: "<red>Nenhum pedido de teleporte ativo."
      many_found: "<gold>Vários pedidos encontrados: <yellow><list></yellow>."
      teleport_here_received: |
        <dark_aqua>Você recebeu um pedido para <yellow><bold>você</bold></yellow> se teleportar até <yellow><username></yellow>.
        <dark_aqua>Digite <click:run_command:'/teleporteaceitar <username>'><hover:show_text:'<gold><yellow>Clique</yellow> para <green>aceitar</green> o teleporte.'><green>/teleporteaceitar</green> para aceitar</hover></click> ou <click:run_command:'/teleporterecusar <username>'><hover:show_text:'<gold><yellow>Clique</yellow> para <red>recusar</red> o teleporte.'><red>/teleporterecusar</red> para recusar</hover></click>.
      request_cancelled: "<gold>Pedido de teleporte cancelado!"
      sent_requests_cancelled: "<gold>Os pedidos enviados foram cancelados."
    back:
      no_back_location: "<red>Não há localização para voltar."
      back_is_death_location: "<red>Você não tem permissão para voltar ao local de morte."
    homes:
      help: "<gold>Para criar uma casa, <click:suggest_command:'/criarcasa nome'><hover:show_text:'<gold><yellow>Clique</yellow> para criar uma casa.'>digite <yellow><bold>/criarcasa</bold></yellow></hover></click> e assim poderá voltar para ela <click:suggest_command:'/casa casa'><hover:show_text:'<gold><yellow>Clique</yellow> aqui para se teleportar até a casa.'>digitando <yellow><bold>/casa</bold></yellow></hover></click>!"
      list: |
        <gold>Para <click:suggest_command:'/criarcasa nome'><hover:show_text:'<gold><yellow>Clique</yellow> para criar uma casa.'><green>criar</green> mais casas, digite <red><bold>/criarcasa</bold></red></hover></click>. Para <click:suggest_command:'/deletarcasa nome'><hover:show_text:'<gold><yellow>Clique</yellow> para apagar uma casa.'><red>apagar</red> casas, digite <red><bold>/deletarcasa</bold></red></hover></click>.
        <gold>Casas disponíveis: <yellow><list></yellow>
      at_max_capacity: "<red>Você atingiu o número máximo de casas, <click:suggest_command:'/deletarcasa nome'><hover:show_text:'<gold><yellow>Clique</yellow> para apagar uma casa.'>para apagar casas, digite <red><bold>/deletarcasa</bold></red></hover></click>."
      invalid_home_name: "<red>Nome de casa inválido: não utilize caracteres especiais!"
      create_help: "<gold>Digite /criarcasa (nome) para criar uma casa."
      created: "<gold>Casa criada! Você pode teleportar até ela no futuro digitando <yellow><bold>/casa</bold></yellow>!"
      already_exists: "<red>Casa já existe. <gold>Para substituí-la, digite o comando novamente nos próximos segundos."
      deleted: "<gold>Casa removida."
      not_found: "<red>Casa não encontrada ou você perdeu permissão para acessar esta casa."
      delete_help: |
        <gold>Para remover uma casa, <click:suggest_command:'/deletarcasa nome'><hover:show_text:'<gold><yellow>Clique</yellow> aqui para remover uma casa'>digite <red><bold>/deletarcasa (nome)</bold></red>.</hover></click>
        <gold>Casas disponíveis: <yellow><list></yellow>
    warps:
      manage:
        help: "<gold>Uso: <yellow>/criarportal (nome)</yellow> ou <yellow>/deletarportal (nome)</yellow>."
        success: "<gold>Portal alterado com sucesso!"
        failure: "<red>Falha ao acessar banco de dados."
      list: "<gold>Portais disponíveis: <yellow><list></yellow>"
      failed_to_retrieve: "<red>Falha ao obter lista."
      not_found: "<red>Portal não encontrado."
    worlds:
      list: "<gold>Mundos disponíveis: <yellow><list></yellow>."
      not_found: "<red>Mundo não encontrado."
  totem:
    totem_in_cooldown: "<red>Seu totem está em <i>cooldown</i> e não fez efeito."
    totem_entered_in_cooldown: "<red>Seu totem entrou em <i>cooldown</i> e não fará efeito por alguns minutos."
  kick_messages:
    could_not_load_profile: "<red>Não foi possível carregar seu perfil!"
