configuration:
  database:
    mongo_uri: 'mongodb://localhost:27017'
    database_name: 'serverNameDb'
    is_exception_fatal: false
    player_collection_name: 'combatPlayerProfiles'
    kit_collection_name: 'inventoryKits'
    save_player_timer_task_ticks: 3600

language:
  failed_to_retrieve_profile: "<red>Falha ao carregar seu perfil!"
  something_went_wrong: "<red>Alguma coisa deu errado!"
  player_only_command: "<red>Este comando sรณ pode ser executado por jogadores."
  command:
    kit:
      help: "<gold>Uso: <yellow>/kit (nome)</yellow>"
