configuration:
  chat_limiter:
    message_amount: 4
    time_amount_millis: 12000
    min_message_length: 3
  comparator:
    min_length_to_compare: 4
    min_char_differences: 3
  universal_chat:
    format: "<hover:show_text:'<gold><yellow>Clique</yellow> para enviar uma mensagem privada para <yellow><bold><username></bold></yellow>!'><click:suggest_command:'/msg <username> '><gold>!! <gray>(</gray><gold><server></gold><gray>)</gray> <gold><<yellow><prefix><username><suffix><gold>></gold></click></hover><reset> <message>"
    prefix: '!!'
  global_chat:
    format: "<hover:show_text:'<gold><yellow>Clique</yellow> para enviar uma mensagem privada para <yellow><bold><username></bold></yellow>!'><click:suggest_command:'/msg <username> '><dark_aqua>! <</dark_aqua><yellow><prefix><username><suffix></yellow><dark_aqua>></dark_aqua></click></hover><reset> <message>"
    spy_format: "<hover:show_text:'<gold><yellow>Clique</yellow> para enviar uma mensagem privada para <yellow><bold><username></bold></yellow>!'><click:suggest_command:'/msg <username> '><gray>! (<server>) <<prefix><username><suffix><gray>></gray><reset> <gray><message></gray>"
    prefix: '!'
  other_server_chat:
    spy_format: "<gray><hover:show_text:'<gold><yellow>Clique</yellow> para enviar uma mensagem privada para <yellow><bold><username></bold></yellow>!'><click:suggest_command:'/msg <username> '>(<server>) <username>:</click></hover> <message></gray>"
  local_chat_format: "<hover:show_text:'<gold><yellow>Clique</yellow> para enviar uma mensagem privada para <yellow><bold><username></bold></yellow>!'><click:suggest_command:'/msg <username> '><yellow><prefix><username><suffix></yellow><gray>:</gray></click></hover><reset> <gray><message></gray>"
  direct_messages:
    reply_time_amount_seconds: 240
  blocked_words:
    - puta
    - whore
    - prostituta
    - cacete
    - caceta
    - fudida
    - fudido
    - fodida
    - fodido
    - fudeu
    - fodeu
    - fodendo
    - fudendo
    - foda
    - foder
    - fode
    - hooker
    - bicha
    - bixa
    - buceta
    - caralho
    - caralha
    - porra
    - viado
    - viada
    - veado
    - veada
    - viadao
    - veadao
    - xoxota
    - xana
    - chochota
    - xochota
    - choxota
    - chana
    - xereca
    - xerereca
    - xavasca
    - chereca
    - cherereca
    - chavasca
    - baitola
    - bisca
    - biscate
    - busseta
    - bosseta
    - cadela
    - xota
    - chota
    - corna
    - corno
    - gay
    - gey
    - guei
    - guay
    - guai
    - gai
    - gei
    - leprosa
    - leproso
    - merda
    - merd
    - mierd
    - mierda
    - merdao
    - bostao
    - bosta
    - otaria
    - otario
    - retardado
    - retardada
    - veado
    - quenga
    - kenga
    - fedido
    - fedida
    - mulata
    - mulato
    - nega
    - negao
    - nego
    - negona
    - burra
    - burro
    - anus
    - preta
    - encardido
    - encardida
    - fuleiro
    - fuleira
    - fulero
    - fulera
    - foleiro
    - foleira
    - folero
    - folera
    - vadia
    - vadio
    - raba
    - rabo
    - suruba
    - surubao
    - soruba
    - sorubao
    - suroba
    - surobao
    - cachorra
    - vagabunda
    - vagabundo
    - corninho
    - corninha
    - cornao
    - cornona
    - safada
    - safado
    - idiota
    - estupido
    - estupida
    - istupido
    - istupida
    - imbecil
    - cuzao
    - cuzona
    - fdp
    - fds
    - vsfd
    - sfd
    - vsf
    - tnc
    - vtnc
    - putinha
    - putinho
    - putona
    - putao
    - fela
    - poha
    - medrosa
    - medroso
    - medroza
    - medrozo
    - putaria
    - putasa
    - putassa
    - putaca
    - pariu
    - arrombado
    - arrombada
    - arombado
    - arombada
    - pobre
    - falido
    - falida
    - chupa
    - xupa
    - hermafrodita
    - emafrodita
    - aborto
    - aborta
    - abortado
    - abortada
    - arregao
    - arregona
    - aregao
    - aregona
    - anal
    - lixo
    - lixao
    - lixona
    - licho
    - lichao
    - lichona
    - gozei
    - goza
    - gozar
    - gozo
    - goso
    - gosei
    - gosa
    - gosar
    - zoofilo
    - zoofila
    - zofilo
    - zofila
    - garai
    - carai
    - karai
    - pinto
    - piroca
    - penis
    - pirocao
    - birosca
    - pintao
    - pauzao
    - pausudo
    - pauzudo
    - pausao
    - piranha
    - piranhona
    - escroto
    - escrota
    - escrotao
    - retardado
    - retardada
    - leproso
    - leprosa
    - macaco
    - macaca
    - sexo
    - secsu
    - arrombado
    - arrombada
    - arombado
    - arombada
    - retarda
    - debiloide
    - gostosa
    - gostoso
    - porno
    - pornozao
    - lesbica
    - lesbico
    - mama
    - mamando
    - gostosona
    - gostozona
    - zona
    - putaria
    - gostozao
    - gostosao
    - cock
    - ball
    - bola
    - novinha
    - 9vinha
    - 9inha
    - rabuda
    - peluda
    - peludo
    - lambuzar
    - lambuza
    - grelo
    - greluda
    - grelao
    - crianca
    - criança
    - random
    - ramdom
    - randon
    - casada
    - meti
    - meter
    - barata
    - barato
    - easy
    - monobola
    - monoball
    - boludo
    - boluda
    - burro
    - burra
    - babaca
    - cretino
    - cretina
    - piroquinha
    - pirokinha
    - vagina
    - nude
    - nigga
    - niga
    - nigger
    - niger
    - bunda
    - bumbum
    - cu
    - fude
    - fuder
    - merdinha
    - desgraça
    - desgraçado
    - desgraçada
    - peste
    - praga
    - broxa
    - piriguete
    - pirigete
    - altista
    - ass
    - pussy
    - pica
    - dick
    - fuck
    - fucking
    - fucked
    - poura
    - porra
    - ez
    - easy
    - probe
    - perereca
    - fodase

language:
  console_name: 'administração'
  unknown_server_name: 'limbo?'
  no_permission: "<red>Você não possui permissão."
  messages_too_small: "<red>Mensagens muito pequenas são ignoradas!"
  messages_too_frequent: "<red>Mensagens enviadas muito rapidamente!"
  messages_too_similar: "<red>Mensagens muito parecidas!"
  players_only: "<red>Comando disponível apenas para jogadores!"
  direct_messages:
    help: "<gold>Digite <yellow><bold><click:suggest_command:'/mensagem <nome> <mensagem>'><hover:show_text:'<gold>Exemplo: <yellow><bold>/msg rflsms tudo bem?'>/mensagem <nome> <mensagem></hover></click></gold>"
    reply_help: "<gold>Digite <yellow><bold><click:suggest_command:'/responder <mensagem>'><hover:show_text:'<gold>Exemplo: <yellow><bold>/r estou bem sim, e você?'>/responder <mensagem></hover></click></bold></yellow>, a mensagem irá para a última pessoa com quem falou.</gold>"
    no_player_found: "<red>Jogador não encontrado!"
    outgoing_format: "<dark_aqua><hover:show_text:'<gold><yellow>Clique</yellow> para enviar uma mensagem para <yellow><bold><receiver></bold></yellow></gold>'><click:suggest_command:'/msg <receiver> '><bold>você</bold> <gray>-></gray> <receiver></click></hover></dark_aqua><gray>: <message>"
    incoming_format: "<dark_aqua><hover:show_text:'<gold><yellow>Clique</yellow> para enviar uma mensagem para <yellow><bold><sender></bold></yellow></gold>'><click:suggest_command:'/msg <sender> '><sender> <gray>-></gray> <bold>você</bold></click></hover></dark_aqua><gray>: <message>"
    spy_format: "<dark_aqua><hover:show_text:'<gold><yellow>Clique</yellow> para enviar uma mensagem para <yellow><bold><sender></bold></yellow></gold>'><click:suggest_command:'/msg <sender> '><sender></click></hover> <gray>-></gray> <hover:show_text:'<gold><yellow>Clique</yellow> para enviar uma mensagem para <yellow><bold><receiver></bold></yellow></gold>'><click:suggest_command:'/msg <receiver> '><receiver></click></hover></dark_aqua><gray>: <gray><message></gray>"
