configuration:
  database:
    mongo_uri: 'mongodb://localhost:27017'
    mongo_database: 'proxyDb'
    player_profile_collection: 'loginProfiles'
  allowed_java_usernames_regex: '^\!?[A-Za-z0-9_]{3,16}$'
  default_server_name: 'survival'
  offline_players:
    offline_players_login_server_name: 'login'
    offline_allowed_commands:
      - login
      - l
      - log
      - registrar
      - cadastrar
      - reg
      - register
    minutes_between_joins_to_auto_login: 45
    max_accounts_registered_per_address: 1
  muted_blocked_commands:
    - msg
    - tell
    - pm
    - dm
    - reply
    - r
    - w
    - whisper
    - responder
    - message
    - mensagem
    - tp
    - tpa
    - tpyes
    - tpsim
    - tpask
    - tpaqui
    - tphere
    - tpahere
    - tpaccept
    - tpaceitar
    - teleporteaqui
    - teleporthere
    - teleporte
    - teleport
    - teleportaccept
    - teleporteaceitar
    - teleportaceitar

language:
  generic:
    date_time_formatter: "EEE', 'dd' de 'MMM' às 'H'h'mm"
    no_permission: "<red>Você não possui permissão."
    no_player_found: "<red>Nenhum jogador encontrado."
    console_name: "Console (administração)"
    report_reason_unknown: "não especificado"
    no_expiration_date: "data não especificada"
  commands:
    players_only: "<red>Comando pode ser executado apenas por jogadores!"
    offline_players_only: "<red>Comando pode ser executado apenas por jogadores piratas!"
    incorrect_pin: "<red>Senha inválida!"
    incorrect_pin_format: "<red>Sua senha deve ter 6 números."
    logged_in: "<green>Login efetuado com sucesso!"
    logged_in_players_only: "<red>Comando pode ser executado apenas por jogadores que usaram <bold>/login</bold>!"
    no_profile_found: "<gold>Não encontramos usuários com este nome."
    failed_to_search_profile: "<red>Falha ao procurar perfil."
    failed_to_save_profile: "<red>Falha ao salvar perfil."
    change_pin:
      help: |
        <gold>Lembre da sua senha anterior, pense numa senha nova de 6 números e digite:
        <yellow><bold>/mudarsenha <antiga> <nova> <nova></bold></yellow>
        <gold>Por exemplo: <yellow>/mudarsenha 000000 123456 123456</yellow>
      invalid_pins: |
        <red>Sua senha nova precisa ser digitada igualmente duas vezes.
        <red>A senha precisa ser 6 números.
        <gold>Exemplo: <yellow><bold>/mudarsenha <antiga> 123456 123456</bold></yellow>
      register_instead: |
        <gold>Você ainda não tem senha cadastrada, digite para cadastrar:
        <yellow><bold>/registrar</bold></yellow>
      success: "<gold>Senha alterada com sucesso!"
    register:
      help: |
        <gold>Pense e memorize uma senha de 6 números e digite duas vezes:
        <gold>Por exemplo: <yellow>/registrar 123456 123456</yellow>
      invalid_pins: |
        <gold>Sua senha deve conter 6 números e ser digitada duas vezes de forma igual:
        <gold>Por exemplo: <yellow>/registrar 012345 012345</yellow>
      max_accounts_per_address_reached: "<red>Número máximo de contas para seu endereço atingido."
      login_instead: "<gold>Conta já cadastrada! Digite <yellow><bold>/login</bold></yellow> e sua senha para entrar."
      change_pin_instead: "<gold>Conta já cadastrada! Digite <yellow><bold>/mudarsenha</bold></yellow> para alterar a senha."
    login:
      help: "<gold>Lembre-se da senha cadastrada e digite: <yellow><bold>/login 123456</bold></yellow> trocando pela <yellow><underline>sua</underline></yellow> senha de 6 números."
      register_instead: "<gold>Conta ainda não cadastrada! Digite <yellow><bold>/registrar</bold></yellow> para registrar"
      already_logged_in: "<gold>Já está online, bom jogo :)"
      no_server_available: |
        <red>Falha ao transferir: servidor não encontrado.
        <red>Digite <yellow>/server</yellow> para mudar de servidor manualmente.
      weak_pin_used: "<red>SENHA OBVIA DETECTADA! Altere sua senha digitando <yellow>/mudarsenha</yellow>!</red>"
    unban:
      help: "<gold>Uso: <yellow>/unban <nome></yellow>"
    ban:
      help: "<gold>Uso: <yellow>/ban <nome> <razão></yellow>"
      player_offline: "<red>Jogador está offline, você não possui permissão."
    seen:
      help: "<gold>Uso: <yellow>/seen <nome/uuid></yellow>"
      profile: |
        <gold><click:copy_to_clipboard:'<user_id>'><hover:show_text:'<gold><yellow>Clique</yellow> para copiar o nome</gold>'><yellow><user_name></yellow></hover></click> (<click:copy_to_clipboard:'<user_id>'><hover:show_text:'<gold><yellow>Clique</yellow> para copiar UUID</gold>'><yellow><user_id></yellow></hover></click>):
        <gold>* Último IP: <click:copy_to_clipboard:'<user_ip>'><hover:show_text:'<gold><yellow>Clique</yellow> para copiar o IP</gold>'><yellow><user_ip></yellow></hover></click>
        <gold>* Último servidor: <yellow><server_name></yellow>
        <gold>* Tempo em jogo: <yellow><play_time></yellow>
        <gold>* Última vez online: <yellow><join_date></yellow>
        <gold>* Última saída: <yellow><quit_date></yellow>
        <gold>* Ocorrências:
        <report_entries>
      report_entry: "<hover:show_text:'<gold>Status: <yellow><active></yellow></gold><newline><gold>Operador: <yellow><reporter_name></yellow></gold><newline><gold>Data: <yellow><date></yellow></gold><newline><gold>Válido até <yellow><expiration_date></yellow></gold>'><gold><yellow><type></yellow> por <yellow><reason></yellow></gold></hover>"
    temporary_ban:
      help: "<gold>Uso: <yellow>/tempban <nome> <tempo> <razão></yellow>"
      player_offline: "<red>Jogador está offline, você não possui permissão."
    unmute:
      help: "<gold>Uso: <yellow>/unmute <nome></yellow>"
    mute:
      help: "<gold>Uso: <yellow>/mute <nome> <tempo> <razão></yellow>"
      player_offline: "<red>Jogador está offline, você não possui permissão."
    kick:
      help: "<gold>Uso: <yellow>/kick <nome> <razão>"
    list_server_players: "<gold>Servidor <server_name> (<size>): <yellow><player_list></yellow>"
    player_punished: "<gold>Jogador <yellow><player></yellow> punido."
    player_unpunished: "<gold><player> teve sua punição revogada."
    player_is_not_punished: "<red><player> não está punido."
    ping:
      help: "<gold>Uso: <yellow>/ping [nome]</yellow></gold>"
      self_ping: "<gold>Seu ping é <yellow><ping> ms</yellow>.</gold>"
      other_player_ping: "<gold>O ping de <yellow><username></yellow> é <yellow><ping> ms</yellow>.</gold>"
  kick_messages:
    could_not_check_mojang: |
      <red>Falha ao consultar servidor da Microsoft.
      <red>Tente novamente mais tarde!
    invalid_java_prefix: |
      <red>Nome inválido para Java Edition.
      <red>Troque de nome e entre novamente.
    invalid_java_username: |
      <red>Nome inválido.
      <red>Troque de nome e entre novamente.
    failed_to_retrieve_player_profile: |
      <red>Falha ao consultar seu perfil.
      <red>Tente novamente mais tarde!
    failed_to_save_player_profile: |
      <red>Falha ao salvar seu perfil.
      <red>Tente novamente mais tarde!
    login_server_unavailable: |
      <red>Servidor para login indisponível.
      <red>Tente novamente mais tarde!
  punishment:
    logged_off: "<gold>Você não efetuou login! Digite <yellow><bold>/registrar</bold></yellow> ou <yellow><bold>/login</bold></yellow>!"
    kicked: |
      <red>Você foi expulso por <yellow><reporter></yellow>
      <red>por <yellow><reason></yellow>
    banned: |
      <red>Você foi banido por <yellow><reporter></yellow>
      <red>pelo motivo <yellow><reason></yellow>
      <red>até <yellow><expiration_date></yellow>
    muted: "<red>Você foi silenciado por <yellow><reporter></yellow> pelo motivo <yellow><reason></yellow> até <yellow><expiration_date></yellow>."
    commands_muted: "<red>Você não pode executar este comando enquanto está silenciado."
